React Redux -  Capstone Project
for-ashraf/react-capstone-arxiv-api- pull request #3
Opened 2022-09-01 22:06 UTC by for-ashraf

In this PR, I have incorporated the following:

Follows Template design main guidelines (Layout, font). ✔️
Shows a list of characters and their respective names and ids. ✔️
You can filter characters by name. ✔️
You can navigate through pages by clicking on the characters/status. ✔️
When the user clicks on the "Back" button (<), the user navigates to the home page. ✔️
All testings are correctly implemented and passing. ✔️
The project is a single-page application (SPA) built with React and Redux. ✔️
The data retrieved from the API is stored in the Redux store. ✔️
Every page has a unique route within the SPA. ✔️
[You can check the LIVE VERSION right here]()
[You can check the VIDEO DESCRIPTION right here]()

Original design idea by [Nelson Sakwa on Behance](https://www.behance.net/sakwadesignstudio).

2022-09-01 23:26 UTC, BenMukebo requested changes
## Hi @for-ashraf, 

You did a great job so far 👏🏼 👏🏼
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>


### To Highlight 🎉

- Git flow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and summary. ✔️
- Good presentation video. ✔️ 
- Your Design looks awesome, keep rocking :rocket: 

## STATUS: CHANGES REQUESTED  ♻️ 
_Please Check the comments under the review and make all required changes_
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers :clinking_glasses:  and Happy coding!!! :dancers:💻  

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me @BenMukebo when you comment so I can receive the notification.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-01 23:26 UTC, BenMukebo commented on README.md
> +
- [ ] Great job with the video presentation 📸 👍🏻  however your deployed link present in the README is directing me to the README page. Kindly make sure the project is deployed properly using Heroku, Netlify, or GitHub Pages. 👍🏻 💯

2022-09-01 23:26 UTC, BenMukebo commented on src/__tests__/App.test.js
> +
- [ ] Actually, I'm getting some failed tests when I run `npm run test`  but if all the tests run fine on your local machine, kindly attach a screenshot for the second reviewer to skip this otherwise make sure to fix this 👍🏻 

![18](https://user-images.githubusercontent.com/79058364/188028875-74e85fe0-a4b1-4a05-85d2-7b6e9296aada.png)

2022-09-02 02:35 UTC, mahbubul14 requested changes
Hi @for-ashraf ,

Great work on making the changes requested by the previous reviewer 👏

You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.

# Required Changes ♻️

- [ ] Kindly check the inline comments under the review. :arrow_down: 

###  To Highlights
:heavy_check_mark: No linter error.
:heavy_check_mark: Professional Readme file.
:heavy_check_mark: Descriptive PR title & description.

### Optional suggestions

Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better.

- [ ] The commit message should be written in the imperative tense and the first letter should also be capitalized. `Ex: "Fix bug" instead of "Fixed bug / bug fix".` [For more details...](https://www.freecodecamp.org/news/level-you-up-to-awesome-commit-messages-a85558cb90e8)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. You can also reach me on [slack](https://microverse-students.slack.com/team/U01J39GL614)

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-09-02 02:35 UTC, mahbubul14 commented on src/__tests__/App.test.js
> +
- [ ] I am also getting the same error as the previous reviewer said. Kindly fix the issue. You can also check [this article](https://jestjs.io/docs/snapshot-testing) to get a better understanding of how to write snapshot tests. :+1: 

![test](https://user-images.githubusercontent.com/70483835/188046178-9ac7ce35-8334-4921-baef-d06445316871.png)

2022-09-02 07:56 UTC, ShoiraTa approved these changes
## **STATUS: APPROVED  🟢 ** 
------
### Hi @for-ashraf , 

**Great work on making the changes requested by a previous reviewer 👏🏻** 

All specs are passing successfully now 👍🏻 

Your project is complete! . There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

![5SW](https://user-images.githubusercontent.com/77038610/154919611-7d0675af-6364-45a3-92d6-eccd9b743ced.gif)

**Cheers and Happy coding! :clap: :clap: :clap:**

Feel free to leave any questions or comments in the PR thread by mentioning my Github username if something is not 100% clear.
***
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have  limited number of  reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-02 07:59 UTC, merged